name: Publish Python Package

on:
  push:
    branches: [main, wip]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-24.04
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Create venv
        run: uv venv
      - name: Install build dependencies
        run: uv pip install setuptools wheel build
      - name: Build the package
        run: uv run python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: dist/

  publish-to-testpypi:
    name: Publish to PyPI-Test
    runs-on: ubuntu-24.04
    needs: [build]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/simplefin-python
    permissions:
      id-token: write
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true