name: Test

on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287 # v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
